import { Tour } from 'nextstepjs';

export const tourSteps: Tour[] = [
  {
    tour: 'onboarding',
    steps: [
      {
        icon: '👋',
        title: 'Welcome to Your Community!',
        content: 'Congratulations on creating your dance community! Let me show you around the key features to help you get started.',
        selector: '#community-header',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '✍️',
        title: 'Share Your Thoughts',
        content: 'This is where you can create posts to share updates, tips, or start discussions with your community members.',
        selector: '#write-post',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '🏷️',
        title: 'Organize with Categories',
        content: 'Use thread categories to help organize different types of discussions - from technique tips to event announcements.',
        selector: '#thread-categories',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '🧭',
        title: 'Navigate Your Community',
        content: 'Use these tabs to navigate between your community discussions, classroom content, and community information.',
        selector: '#navigation-tabs',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '🎓',
        title: 'Your Classroom',
        content: 'The Classroom tab is where you can share structured learning content, tutorials, and courses for your students.',
        selector: '#tab-classroom',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: 'ℹ️',
        title: 'Community Information',
        content: 'The About tab contains your community description, rules, and other important information for new members.',
        selector: '#tab-about',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '⚙️',
        title: 'Community Settings',
        content: 'Click here to access your community settings where you can customize various aspects of your community.',
        selector: '#settings-button',
        side: 'left',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '🎨',
        title: 'General Settings',
        content: 'In the General tab, you can update your community name, description, and branding to reflect your teaching style.',
        selector: '#settings-general',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '💳',
        title: 'Subscription Settings',
        content: 'Set up your subscription pricing and billing options to monetize your community and teaching content.',
        selector: '#settings-subscriptions',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '🏷️',
        title: 'Thread Categories',
        content: 'Organize your community discussions with custom thread categories. You can create categories for different dance styles, events, or topics.',
        selector: '#settings-thread_categories',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '👥',
        title: 'Track Your Growth',
        content: 'Keep an eye on your member count here. Watch it grow as more dancers discover your community!',
        selector: '#member-count',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '🚀',
        title: 'Share Your Community',
        content: 'Use this button to share your community link with others. The more you share, the more dancers you can reach and teach!',
        selector: '#community-sharing',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
    ],
  },
];